/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e205707;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class HeroTest {
    /**
     * Heroクラスからオブジェクトを生成し、
     * attackWithWeponSkillを3回実行し、
     * 3回ともattackの150%ダメージになっていることを確認する
     */
    @Test
    void attackWithWeponSkillTest(){
        int testAttack = 10;
        int testhitPoint = 1000;
        Warrior demoWarrior = new Warrior("tes", 10, testAttack);
        Enemy demoEnemy = new Enemy("tet", testhitPoint, 0);
        for (int i = 0; i < 3; i++ ){
            demoWarrior.attackWithWeponSkill(demoEnemy);
            
            assertEquals(demoEnemy.hitPoint, testhitPoint - (int) (testAttack * 1.5));
        }
        
    }

}
